source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'CampMinder', path: '../../'

group :development, :test do
  gem 'rspec', '~> 3.1'
  gem 'rspec-mocks', '~> 3.1'
  gem 'dotenv', '~> 1.0'
end
