module CampMinder
  BUSINESS_PARTNER_ID = ENV["CAMPMINDER_BUSINESS_PARTNER_ID"]
  SECRET_CODE = ENV["CAMPMINDER_SECRET_CODE"]
  WEB_SERVICE_URL = ENV["CAMPMINDER_WEB_SERVICE_URL"]
  REDIRECTION_URL = ENV["CAMPMINDER_REDIRECTION_URL"]
end
